#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Apr 14 10:40:03 CEST 2022
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim ALU_TEST_behav -key {Behavioral:sim_1:Functional:ALU_TEST} -tclbatch ALU_TEST.tcl -view /home/guerbett/Repositories/c-compiler-project/archi_mat/V1/microprocesseur/ALU_TEST_behav.wcfg -log simulate.log
